### PR TITLE
feat: added dark mode

### LINKED ISSUE #6: Add dark mode to the docs site
Now looks like that...

buzz-notify-henna vercel app_

### PR DESCRIPTION
**Pull request by RajMhatre20**
closes #6

### CODE REVIEW

**Comment by RajMhatre20** [comment]
why didn't the check pass?

**Comment by eliutgon** [comment]
@RajMhatre20 please see and fix the errors.

Consider use this https://squoosh.app to optimize the size of the images, they take up a lot of space...

**Comment by RajMhatre20** [comment]
I've fixed the errors and reduced the size of the icons.

**Comment by eliutgon** [comment]
@RajMhatre20 thanks for your contribution!

**Pull request merged**
