### PR TITLE
Add config for Prettier

### LINKED ISSUE #10: Add config for Prettier
Add config file for Prettier to prevent conflicts between tab spaces and single/double quotes

### PR DESCRIPTION
**Pull request by omeiirr**
closes #10 

- [x] Set tab width to 2
- [x] Prevent single quotes
- [x] Add pre-push git hook

### CODE REVIEW

**Comment by omeiirr** [comment]
@eliutgon Any tips on how to resolve the first failed check?

**Comment by eliutgon** [comment]
> @eliutgon Any tips on how to resolve the first failed check?

You need to change the PR title, using a semactic style. In this case is **style: add config for Prettier**

**Comment by eliutgon** [comment]
@omeiirr I recommend you to use a git hook before the push to execute the format in the `src`

**Comment by omeiirr** [comment]
@eliutgon Added a new semantically correct [commit](https://github.com/eliutgon/buzz-notify/pull/11/commits/5a7d73cefce2954082168450beb36169b6e87935) and it has passed the tests.

Thanks for the git-hooks tip 😉
I didn't know about that.

**Pull request closed without merging**
